fix(postgres): reconnect on OperationalError too
projectcaluma/manabi pull request #139
Opened 2022-12-01 15:03 UTC by ganwell

2022-12-01 16:30 UTC, anehx commented
@winged could you take a look at this as well?

2022-12-02 07:26 UTC, winged requested changes
Code looks good, I just think that we should drop some hints for future readers / admins regarding what's going on

2022-12-02 07:26 UTC, winged commented on manabi/lock.py
> +            self._connection.close()
Might need a comment here to un-confuse future readers. Specifically, that the `AttributeError` from not having `self._connection` at all on first call is also "ok" here
```suggestion
            # Try to close existing connection if there is one. 
            # On first call, this causes a AttributeError, which we can ignore as well
            self._connection.close()
```

2022-12-02 10:27 UTC, ganwell commented
@winged I should have addressed everything.

2022-12-02 10:40 UTC, winged approved these changes

2022-12-02 10:40 UTC, merged